package com.ec.entity;

import java.util.Date;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Project_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.To_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Send_Time
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Subject
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Content
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_id
     *
     * @return the value of mail.Mail_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_id
     *
     * @param mailId the value for mail.Mail_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Project_id
     *
     * @return the value of mail.Project_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Project_id
     *
     * @param projectId the value for mail.Project_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.To_id
     *
     * @return the value of mail.To_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.To_id
     *
     * @param toId the value for mail.To_id
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Send_Time
     *
     * @return the value of mail.Send_Time
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Send_Time
     *
     * @param sendTime the value for mail.Send_Time
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Subject
     *
     * @return the value of mail.Subject
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Subject
     *
     * @param subject the value for mail.Subject
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Content
     *
     * @return the value of mail.Content
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Content
     *
     * @param content the value for mail.Content
     *
     * @mbggenerated Thu Mar 29 08:58:49 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}